### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by bmos299** [ibm-hcbt/cloud-pak-sandboxes#13]
Description:
https://github.com/ibm-hcbt/cloud-pak-sandboxes/blob/master/scripts/iaf/README.md  

In Step 3:
3. Prerequisites for installing AI components (optional)

Go here for details.

Problem:
Clicking here presents, 

```
We're sorry!

To view the documentation for IBM Automation Foundation Entitled, you need to be authorized.
Please sign in to IBM with your IBM ID.

If you can't view the documentation after you sign in, contact IBM Documentation support to request access to this documentation. 
```

**Comment by annumberhocker** [comment]
This link flakiness has to do the the docs.  Sometimes it works, sometimes it doesn't.  They are working on it:
![Uploading image.png…]()
